api/urls.py
from django.urls import path, include
from api import views as api_views

urlpatterns = [
    path('property/',api_views.PropertyListAPIView.as_view(), name = 'property' ),
    path('property/<int:pk>',api_views.PropertyDetailAPIView.as_view(), name = 'property-details' ),
    path('city/',api_views.CityListAPIView.as_view(), name = 'city' ),
  


] 

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('blog-list/', views.blog_list, name='blog-list'),
    path('blog-detail/', views.blog_detail, name='blog-detail')
]

evaz/urls.py
from re import template
from django.contrib import admin
from django.urls import path, include
from os import getenv
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.shortcuts import render
from django.views.generic import TemplateView
from django.contrib.sitemaps.views import sitemap
from .sitemaps import StaticSitemap, PropertySitemap

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path(getenv('ADMIN_URL'), admin.site.urls),
    path('robots.txt', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
    path('api/', include('api.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': {'static': StaticSitemap, 'property': PropertySitemap}}, name='django.contrib.sitemaps.views.sitemap')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
) + i18n_patterns(
    path('', include('sale.urls')),
    path('seller/', include('seller.urls')),
    path('info/', include('info.urls')),
    path('blog/', include('blog.urls')),
)


handler404 = lambda request, exception: render(request, '404.html')

info/urls.py
from django.urls import path
from . import views

app_name = 'info'
urlpatterns = [
    path('contact/', views.contact, name='contact')
]

sale/urls.py
from django.urls import path, re_path
from . import views

app_name = 'sale'

urlpatterns = [
    path('', views.home, name='home'),
    path('property-list/', views.property_list, name='property-list'),
    path('property-detail/<int:pk>/<str:slug>/', views.property_detail, name='property-detail'),
    re_path('^file/(?P<file>\w+)\.(?P<extension>\w+)$', views.example)
]

seller/urls.py
from django.urls import path
from . import views

app_name = 'seller'
urlpatterns = [
    path('register/', views.register_page, name='register'),
    path('login/', views.login_page, name='login'),
    path('logout/', views.logout_handler, name='logout'),
    path('profile/', views.profile, name='profile'),
]

templates/layouts/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="{{request.LANGUAGE_CODE}}">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block meta %}{% endblock meta %}
    {% block title %}{% endblock title %}
    
    <!-- Favicon -->
    <link rel="shortcut icon" href="img/favicon.ico" type="image/x-icon">

    <!-- Font awesome -->
    <link href="{% static 'css/font-awesome.css' %}" rel="stylesheet">
    <!-- Bootstrap -->
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">   
    <!-- slick slider -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/slick.css' %}">
    <!-- price picker slider -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/nouislider.css' %}">
    <!-- Fancybox slider -->
    <link rel="stylesheet" href="{% static 'css/jquery.fancybox.css' %}" type="text/css" media="screen" /> 
    <!-- Theme color -->
    <link id="switcher" href="{% static 'css/theme-color/default-theme.css' %}" rel="stylesheet">     

    <!-- Main style sheet -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">    
   
    <!-- Google Font -->
    <link href='https://fonts.googleapis.com/css?family=Vollkorn' rel='stylesheet' type='text/css'>    
    <link href='https://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
    {% block link %}{% endblock link %}

    <!-- HTML5 shim and Respond.js' %} for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js' %} doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="{% static 'https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js' %}"></script>
      <script src="{% static 'https://oss.maxcdn.com/respond/1.4.2/respond.min.js' %}"></script>
    <![endif]-->

  </head>
  <body class="aa-price-range">  
  <!-- Pre Loader -->
  <div id="aa-preloader-area">
    <div class="pulse"></div>
  </div>
  <!-- SCROLL TOP BUTTON -->
    <a class="scrollToTop" href="#"><i class="fa fa-angle-double-up"></i></a>
  <!-- END SCROLL TOP BUTTON -->

  <!-- Start header section -->
  <header id="aa-header">  
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="aa-header-area">
            <div class="row">
              <div class="col-md-6 col-sm-6 col-xs-6">
                <div class="aa-header-left">
                  <div class="aa-telephone-no">
                    <span class="fa fa-phone"></span>
                    1-900-523-3564
                  </div>
                  <div class="aa-email hidden-xs">
                    <span class="fa fa-envelope-o"></span> info@markups.com
                  </div>
                </div>              
              </div>
              <div class="col-md-6 col-sm-6 col-xs-6">
                <div class="aa-header-right">
                  {% if request.user.is_authenticated %}
                    <a href="{% url 'seller:profile' %}" class="aa-register">{{request.user.get_full_name}}</a>
                    <a href="{% url 'seller:logout' %}" class="aa-login">Logout</a>
                  {% else %}
                    <a href="{% url 'seller:register' %}" class="aa-register">Register</a>
                    <a href="{% url 'seller:login' %}" class="aa-login">Login</a>
                  {% endif %}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </header>
  <!-- End header section -->

  <!-- Start menu section -->
  <section id="aa-menu-area">
    <nav class="navbar navbar-default main-navbar" role="navigation">  
      <div class="container">
        <div class="navbar-header">
          <!-- FOR MOBILE VIEW COLLAPSED BUTTON -->
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <!-- LOGO -->                                               
          <!-- Text based logo -->
           <a class="navbar-brand aa-logo" href="{% url 'sale:home' %}"> EV <span>AZ</span></a>
           <!-- Image based logo -->
           <!-- <a class="navbar-brand aa-logo-img" href="{% url 'sale:home' %}"><img src="{% static 'img/logo.png" alt="logo"></a> -->
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul id="top-menu" class="nav navbar-nav navbar-right aa-main-nav">
            <li class="active"><a href="{% url 'sale:home' %}">HOME</a></li>
            <li><a href="{% url 'sale:property-list' %}">PROPERTY LIST</a></li>
            <li><a href="{% url 'blog:blog-list' %}">BLOG</a></li>
            <li><a href="{% url 'info:contact' %}">CONTACT</a></li>
          </ul>                            
        </div><!--/.nav-collapse -->       
      </div>          
    </nav> 
  </section>
  <!-- End menu section -->

  {% block main %}
  
  {% endblock main %}

  <!-- Footer -->
  <footer id="aa-footer">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
        <div class="aa-footer-area">
          <div class="row">
            <div class="col-md-3 col-sm-6 col-xs-12">
              <div class="aa-footer-left">
               <p>Designed by <a rel="nofollow" href="http://www.markups.io/">MarkUps.io</a></p>
              </div>
            </div>
            <div class="col-md-3 col-sm-6 col-xs-12">
              <div class="aa-footer-middle">
                <a href="#"><i class="fa fa-facebook"></i></a>
                <a href="#"><i class="fa fa-twitter"></i></a>
                <a href="#"><i class="fa fa-google-plus"></i></a>
                <a href="#"><i class="fa fa-youtube"></i></a>
              </div>
            </div>
            <div class="col-md-6 col-sm-12 col-xs-12">
              <div class="aa-footer-right">
                <a href="#">Home</a>
                <a href="#">Support</a>
                <a href="#">License</a>
                <a href="#">FAQ</a>
                <a href="#">Privacy & Term</a>
              </div>
            </div>            
          </div>
        </div>
      </div>
      </div>
    </div>
  </footer>
  <!-- / Footer -->

 
  
  <!-- jQuery library -->
  <!--<script src="{% static 'https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js' %}"></script> -->
  <script src="{% static 'js/jquery.min.js' %}"></script>   
  <!-- Include all compiled plugins (below), or include individual files as needed -->
  <script src="{% static 'js/bootstrap.js' %}"></script>   
  <!-- slick slider -->
  <script type="text/javascript" src="{% static 'js/slick.js' %}"></script>
  <!-- Price picker slider -->
  <script type="text/javascript" src="{% static 'js/nouislider.js' %}"></script>
   <!-- mixit slider -->
  <script type="text/javascript" src="{% static 'js/jquery.mixitup.js' %}"></script>
  <!-- Add fancyBox -->        
  <script type="text/javascript" src="{% static 'js/jquery.fancybox.pack.js' %}"></script>
  <!-- Custom js -->
  <script src="{% static 'js/custom.js' %}"></script> 
  {% block script %}{% endblock script %}
  </body>
</html>